import { useMemo, useState } from 'react'

type Tab = 'home'|'care'|'history'|'profile'
type IconName = Tab|'moon'|'send'|'plus'|'shield'|'file'|'pill'|'sleep'|'walk'|'food'|'heart'|'chevron'|'check'
const paths:Record<IconName,React.ReactNode>={
 home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v11h14V10M9 21v-7h6v7"/></>,care:<><path d="M12 21s-7-4-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 11c0 6-7 10-7 10Z"/><path d="M8 13h2l1-3 2 6 1-3h2"/></>,history:<><path d="M3 12a9 9 0 1 0 3-7L3 8"/><path d="M3 3v5h5m4-1v5l3 2"/></>,profile:<><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></>,moon:<path d="M20 16A9 9 0 0 1 8 4a9 9 0 1 0 12 12Z"/>,send:<><path d="m22 2-7 20-4-9-9-4Z"/><path d="m22 2-11 11"/></>,plus:<path d="M12 5v14M5 12h14"/>,shield:<><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,file:<><path d="M6 2h8l4 4v16H6Z"/><path d="M14 2v5h5M9 13h6M9 17h6"/></>,pill:<><path d="m10 21 11-11a4 4 0 0 0-6-6L4 15a4 4 0 0 0 6 6Z"/><path d="m9 10 5 5"/></>,sleep:<><path d="M20 16A9 9 0 0 1 8 4a9 9 0 1 0 12 12Z"/><path d="M16 4h5l-5 5h5"/></>,walk:<><circle cx="13" cy="4" r="2"/><path d="m10 22 1-6-3-3 2-5 4 3 4 1m-5-1-2 5 4 6"/></>,food:<><path d="M6 2v8M3 2v5a3 3 0 0 0 6 0V2M6 10v12M16 2v20m0-20c4 2 5 7 0 10"/></>,heart:<path d="M21 8c0 6-9 13-9 13S3 14 3 8a5 5 0 0 1 9-3 5 5 0 0 1 9 3Z"/>,chevron:<path d="m9 18 6-6-6-6"/>,check:<path d="m5 12 4 4L19 6"/>}
function Icon({name,size=22}:{name:IconName,size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
const slides=[['10 days','You kept showing up','Ten days of checking in with yourself. That consistency is worth celebrating.'],['7.4 hrs','Your sleep is improving','You averaged 34 more minutes of rest than last week. Small changes add up.'],['4 walks','Movement made a difference','On walking days, you reported feeling calmer. Your body noticed the care.']]
const replies=["Thank you for telling me. It sounds like today asked a lot of you. What felt hardest?","I’m glad you checked in. A gentle next step could be water and three slow breaths. What feels manageable?","I can help you notice patterns and prepare questions for your care team, but I can’t diagnose symptoms. When did you notice this?"]
export default function App(){
 const [role,setRole]=useState<'patient'|'parent'|null>(null)
 const [tab,setTab]=useState<Tab>('home'),[slide,setSlide]=useState(0),[text,setText]=useState(''),[taken,setTaken]=useState(false),[uploaded,setUploaded]=useState(false),[bedTime,setBedTime]=useState('21:30'),[sleepReminder,setSleepReminder]=useState(true)
 const [messages,setMessages]=useState([{who:'ai',text:"Hi Maya. I’m here with you. How are your mind and body feeling today?"}])
 const date=useMemo(()=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date()),[])
 function send(){if(!text.trim())return;setMessages(m=>[...m,{who:'you',text:text.trim()},{who:'ai',text:replies[m.length%replies.length]}]);setText('')}
 if(!role)return <RolePicker onChoose={setRole}/>
 if(role==='parent')return <ParentApp onSwitch={()=>setRole(null)}/>
 return <div className="stage"><main className="phone"><header><button className="brand" onClick={()=>setRole(null)}><i><Icon name="heart" size={19}/></i>Luma</button><button className="switch-role" onClick={()=>setRole(null)}>Switch view</button></header><div className="page" key={tab}>
 {tab==='home'&&<><section className="welcome"><small>{date}</small><h1>Good morning, Maya</h1><p>Let’s take today one gentle step at a time.</p></section><article className={`progress s${slide}`}><small>YOUR JOURNEY</small><strong>{slides[slide][0]}</strong><h2>{slides[slide][1]}</h2><p>{slides[slide][2]}</p><div className="dots">{slides.map((_,i)=><button key={i} className={i===slide?'on':''} onClick={()=>setSlide(i)} aria-label={`Progress card ${i+1}`}/>)}</div></article><Title over="DAILY CHECK-IN" title="A safe space to share" end={<span className="private"><Icon name="shield" size={13}/>Private</span>}/><article className="chat"><div className="messages">{messages.map((m,i)=><div className={`message ${m.who}`} key={i}><i>{m.who==='ai'?'✦':'M'}</i><p>{m.text}</p></div>)}</div><div className="chips">{['My sleep','I feel anxious','A small win'].map(x=><button key={x} onClick={()=>setText(x)}>{x}</button>)}</div><div className="composer"><button><Icon name="plus" size={18}/></button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Share what’s on your mind…"/><button className="send" onClick={send}><Icon name="send" size={17}/></button></div><small className="note">Luma supports your care — it does not replace a healthcare professional.</small></article></>}
 {tab==='care'&&<><Hero over="MY CARE" title="Your care, made simpler" sub="Keep your health information and daily routines together."/><button className={`upload ${uploaded?'done':''}`} onClick={()=>setUploaded(true)}><Badge type="lav" icon={uploaded?'check':'file'}/><span><b>{uploaded?'Record added':'Add a medical record'}</b><small>{uploaded?'neurology_visit.pdf • Ready to review':'PDF, photo, or discharge summary'}</small></span><Icon name="chevron" size={18}/></button><Title over="TODAY" title="Your routine" end={<small>2 of 4 complete</small>}/><div className="routines"><Routine icon="pill" type="rose" title="Sertraline" sub="50 mg • 9:00 AM" end={<button className={`check ${taken?'on':''}`} onClick={()=>setTaken(!taken)}>{taken&&<Icon name="check" size={14}/>}</button>}/><Routine icon="sleep" type="blue" title="Sleep" sub="7h 32m last night" end={<button className={`reminder-toggle ${sleepReminder?'on':''}`} onClick={()=>setSleepReminder(!sleepReminder)}><i/></button>} extra={<div className="bedtime-row"><span>Bedtime reminder</span><input aria-label="Bedtime reminder" type="time" value={bedTime} onChange={e=>setBedTime(e.target.value)}/><small>{sleepReminder?'On':'Off'}</small></div>}/><Routine icon="walk" type="green" title="Movement" sub="2,840 steps today" end={<em>57%</em>} extra={<div className="movement-progress"><div><span style={{width:'56.8%'}}/></div><small><b>2,840</b> current <i>Daily target: 5,000</i></small></div>}/><Routine icon="plus" type="gold" title="Add a note" sub="Mood, symptoms, or anything else" end={<Icon name="chevron" size={17}/>}/></div><article className="recipe"><div><small>RECIPE FOR YOU</small><h2>Warm salmon & quinoa bowl</h2><p>Balanced, simple, and selected around your preferences.</p><button>View recipe →</button></div><i><Icon name="food" size={40}/></i></article><p className="warning"><Icon name="shield" size={15}/> Medication schedules and food suggestions must be confirmed with your clinician or pharmacist.</p></>}
 {tab==='history'&&<><Hero over="REFLECTIONS" title="Your journey so far" sub="Look back with kindness. Every check-in is progress."/><div className="week">{['M','T','W','T','F','S','S'].map((x,i)=><div className={i===4?'today':i<4?'logged':''} key={i}><small>{x}</small><b>{25+i}</b><i>{i<5?'•':''}</i></div>)}</div><Title over="THIS WEEK" title="Daily reflections" end={<button className="link">View all</button>}/><div className="timeline"><Day day="29" mood="Calm" cls="calm" title="A steadier day" body="Your morning walk helped quiet the racing thoughts. Sleep: 7h 32m."/><Day day="28" mood="Low energy" cls="low" title="You made space to rest" body="We talked about choosing one manageable task instead of pushing through."/><Day day="27" mood="Hopeful" cls="hope" title="A small win worth keeping" body="You cooked dinner and called a friend. Both helped you feel connected."/></div></>}
 {tab==='profile'&&<><section className="profile"><div>M</div><h1>Maya Chen</h1><p>Taking care, one day at a time</p><small>Member since May 2026</small></section><div className="stats"><span><b>10</b><small>day streak</small></span><span><b>24</b><small>check-ins</small></span><span><b>8</b><small>small wins</small></span></div><Title over="CARE & SUPPORT" title=""/><div className="settings"><Setting icon="heart" type="rose" title="My care team" sub="Dr. Ahmed and 2 supporters"/><Setting icon="shield" type="blue" title="Safety plan" sub="People and steps that help"/></div><Title over="PREFERENCES" title=""/><div className="settings"><Setting icon="moon" type="lav" title="Appearance" sub="System settings"/><Setting icon="shield" type="green" title="Privacy & data" sub="Manage what you share"/></div><button className="urgent">Need urgent help? <b>View crisis resources →</b></button></>}
 </div><nav>{([['home','Home'],['care','My Care'],['history','History'],['profile','Profile']] as [Tab,string][]).map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><i><Icon name={id}/></i>{label}</button>)}</nav></main></div>}
function Hero({over,title,sub}:{over:string,title:string,sub:string}){return <section className="hero"><small>{over}</small><h1>{title}</h1><p>{sub}</p></section>}
function Title({over,title,end}:{over:string,title:string,end?:React.ReactNode}){return <div className="title"><span><small>{over}</small>{title&&<h2>{title}</h2>}</span>{end}</div>}
function Badge({type,icon}:{type:string,icon:IconName}){return <i className={`badge ${type}`}><Icon name={icon}/></i>}
function Routine({icon,type,title,sub,end,extra}:{icon:IconName,type:string,title:string,sub:string,end:React.ReactNode,extra?:React.ReactNode}){return <div className={`routine ${extra?'expanded':''}`}><div className="routine-main"><Badge icon={icon} type={type}/><span><b>{title}</b><small>{sub}</small></span>{end}</div>{extra}</div>}
function Setting(p:{icon:IconName,type:string,title:string,sub:string}){return <button><Badge icon={p.icon} type={p.type}/><span><b>{p.title}</b><small>{p.sub}</small></span><Icon name="chevron" size={17}/></button>}
function Day({day,mood,cls,title,body}:{day:string,mood:string,cls:string,title:string,body:string}){return <article><div className="date"><b>{day}</b><small>AUG</small></div><div><span className={`mood ${cls}`}>{mood}</span><h3>{title}</h3><p>{body}</p><small>3 notes • 6 min chat</small></div></article>}

function RolePicker({onChoose}:{onChoose:(role:'patient'|'parent')=>void}){
 return <div className="stage"><main className="phone role-phone"><div className="role-hero"><i><Icon name="heart" size={28}/></i><small>WELCOME TO LUMA</small><h1>Care feels better<br/>when we do it together.</h1><p>Choose how you’d like to use Luma today.</p></div><div className="role-options"><button onClick={()=>onChoose('patient')}><Badge type="green" icon="profile"/><span><b>I’m a patient</b><small>Check in, track routines, and reflect on your journey.</small></span><Icon name="chevron"/></button><button onClick={()=>onChoose('parent')}><Badge type="lav" icon="heart"/><span><b>I’m a parent or caregiver</b><small>Observe symptoms and follow your child’s progress.</small></span><Icon name="chevron"/></button></div><p className="role-note"><Icon name="shield" size={15}/> Your information stays private and is never shared without permission.</p></main></div>
}

const conditionSymptoms:Record<string,string[]>={
 'Anxiety':['Worry or fear','Restlessness','Avoiding activities','Trouble sleeping','Physical tension'],
 'Depression':['Low mood','Loss of interest','Low energy','Sleep changes','Social withdrawal'],
 'ADHD':['Difficulty focusing','Impulsivity','Restlessness','Task completion','Emotional regulation'],
 'Autism spectrum':['Sensory distress','Communication difficulty','Routine disruption','Social overwhelm','Repetitive behavior'],
 'Epilepsy':['Seizure activity','Confusion','Fatigue','Headache','Sleep disruption'],
 'Migraine':['Head pain','Light sensitivity','Nausea','Aura or vision change','Concentration difficulty'],
 'Traumatic brain injury':['Headache','Memory difficulty','Dizziness','Mood change','Sleep disruption']
}

function ParentApp({onSwitch}:{onSwitch:()=>void}){
 const [condition,setCondition]=useState('Anxiety'),[scores,setScores]=useState<Record<string,number>>({}),[submitted,setSubmitted]=useState(false)
 const symptoms=conditionSymptoms[condition],average=symptoms.reduce((sum,s)=>sum+(scores[s]??2),0)/symptoms.length
 const trend=average<=1.6?{label:'Showing improvement',cls:'better',body:'Today’s observed symptom level is lower than the recent baseline.'}:average<=3.2?{label:'Mostly stable',cls:'stable',body:'Today looks similar to the recent pattern. Keep observing gently.'}:{label:'Needs attention',cls:'worse',body:'Symptoms appear stronger today. Consider contacting the care team.'}
 function changeCondition(next:string){setCondition(next);setScores({});setSubmitted(false)}
 return <div className="stage"><main className="phone parent-phone"><header><button className="brand" onClick={onSwitch}><i><Icon name="heart" size={19}/></i>Luma</button><button className="switch-role" onClick={onSwitch}>Switch view</button></header><div className="page"><Hero over="PARENT & CAREGIVER" title="How is Noah today?" sub="Record what you notice. You don’t need to have all the answers."/><section className="child-card"><div className="child-avatar">N</div><div><b>Noah Chen</b><small>Age 11 • Last check-in yesterday</small></div><button>Change</button></section><Title over="CONDITION" title="What are you tracking?"/><div className="condition-tabs">{Object.keys(conditionSymptoms).map(name=><button className={condition===name?'active':''} key={name} onClick={()=>changeCondition(name)}>{name}</button>)}</div><Title over="TODAY’S OBSERVATIONS" title="Rate each symptom" end={<small>0 none · 5 severe</small>}/><div className="symptom-list">{symptoms.map(symptom=>{const value=scores[symptom]??2;return <label key={symptom}><span><b>{symptom}</b><em className={`level l${value}`}>{['None','Mild','Mild','Moderate','Strong','Severe'][value]}</em></span><input type="range" min="0" max="5" value={value} onChange={e=>{setScores({...scores,[symptom]:Number(e.target.value)});setSubmitted(false)}}/><span className="scale"><i>0</i><i>1</i><i>2</i><i>3</i><i>4</i><i>5</i></span></label>})}</div><button className="review-button" onClick={()=>setSubmitted(true)}>Review today’s pattern</button>{submitted&&<article className={`trend-card ${trend.cls}`}><div className="trend-icon">{trend.cls==='better'?'↘':trend.cls==='stable'?'→':'↗'}</div><div><small>COMPARED WITH THE LAST 7 DAYS</small><h2>{trend.label}</h2><p>{trend.body}</p><button>Share summary with care team →</button></div></article>}<p className="warning parent-warning"><Icon name="shield" size={15}/>This is an observation tool, not a diagnosis. Sudden, severe, or dangerous symptoms need professional or emergency help.</p></div></main></div>
}
