import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles.css'
import './parent.css'
import './care.css'
import './voice-fix.css'
import './history.css'
import './diary-refresh.css'
import './calendar.css'
import './history-navigation.css'
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>)
