import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles.css'
import './parent.css'
import './care.css'
import './voice-fix.css'
import './history.css'
import './diary-refresh.css'
import './calendar.css'
import './history-navigation.css'
import './auth.css'
import './typography.css'
import './record-preview.css'
import './record-guidance.css'
import './meal-plan.css'
import './cognitive-care.css'
import './cognitive-voice.css'
import './cognitive-shell.css'
import './caregiver-mvp.css'
import './community-mvp.css'
import './analytics-mvp.css'
import './changes-readable.css'
import './patient-data-boundary.css'
import './patient-separation.css'
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>)
